mysql: &MYSQL
  adapter: mysql
  username: root
  password:
  host: localhost
  port: 3306

development:
  <<: *MYSQL
  database: freezer_tracking_development

test: &test
  <<: *MYSQL
  database: freezer_tracking_test

cucumber:
  <<: *test